leftnav:
- identifier: f387fe97-bb43-06bf-ce2d-72a6206131c4
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 912d214c-1a10-6553-592a-a36fdeb25ac9
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: d0601f52-ea35-11c2-a5e2-2d928a38ebe7
  name: Calendar and Assignments
  pageRef: /pages/calendar-and-assignments
  weight: 30
- identifier: 4f6da823-6fc5-5d44-e087-5321b8aa24a2
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: c17af3b7-6df3-d2e0-4762-58dcfb1e15ad
  name: Projects
  pageRef: /pages/projects
  weight: 50
